apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2
    chart: loki-stack
    helm:
      values: |
        loki:
          enabled: true
          image:
            repository: grafana/loki
            tag: 2.10.2
            pullPolicy: IfNotPresent
          
          config:
            server:
              http_listen_port: 3100
            
            ingester:
              lifecycler:
                address: 127.0.0.1
                ring:
                  kvstore:
                    store: inmemory
                  replication_factor: 1
                final_sleep: 0s
              chunk_idle_period: 1h
              max_chunk_age: 1h
              chunk_target_size: 1048576
              chunk_retain_period: 30s
            
            schema_config:
              configs:
                - from: 2020-10-24
                  store: boltdb-shipper
                  object_store: filesystem
                  schema: v11
                  index:
                    prefix: index_
                    period: 24h
            
            storage_config:
              boltdb_shipper:
                active_index_directory: /loki/index
                cache_location: /loki/cache
                shared_store: filesystem
              filesystem:
                directory: /loki/chunks
            
            limits_config:
              enforce_metric_name: false
              reject_old_samples: true
              reject_old_samples_max_age: 168h
              ingestion_rate_mb: 16
              ingestion_burst_size_mb: 32
              per_stream_rate_limit: 16MB
              per_stream_rate_limit_burst: 32MB
              max_streams_per_user: 0
              max_entries_limit_per_query: 5000
              max_query_parallelism: 32
              max_query_length: 721h
            
            compactor:
              working_directory: /loki/compactor
              shared_store: filesystem
              retention_enabled: true
              delete_request_store: filesystem
              retention_delete_delay: 2h
              delete_request_cancel_period: 24h
              compaction_interval: 10m
              max_compaction_parallelism: 1
              retention_delete_worker_count: 150
            
            ruler:
              storage:
                type: local
                local:
                  directory: /loki/rules
              enable_api: true
              enable_alertmanager_v2: true
              alertmanager_url: http://alertmanager.monitoring.svc.cluster.local:9093
              ring:
                kvstore:
                  store: inmemory
          
          persistence:
            enabled: true
            storageClassName: local-path
            size: 50Gi
            accessModes:
              - ReadWriteOnce
          
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          
          service:
            type: ClusterIP
            port: 3100
            portName: http-loki
            targetPort: http-loki
            
        promtail:
          enabled: true
          image:
            repository: grafana/promtail
            tag: 2.10.2
            pullPolicy: IfNotPresent
          
          config:
            server:
              http_listen_port: 3101
            
            clients:
              - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
            
            scrape_configs:
              - job_name: kubernetes-pods
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  - source_labels:
                      - __meta_kubernetes_pod_controller_name
                    regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
                    action: labelmap
                    replacement: ${1}
                  - source_labels:
                      - __meta_kubernetes_pod_label_app_kubernetes_io_name
                    target_label: app
                  - source_labels:
                      - __meta_kubernetes_pod_label_app
                    target_label: app
                  - source_labels:
                      - __meta_kubernetes_namespace
                    target_label: namespace
                  - source_labels:
                      - __meta_kubernetes_pod_name
                    target_label: pod
                  - source_labels:
                      - __meta_kubernetes_pod_node_name
                    target_label: node
                  - source_labels:
                      - __meta_kubernetes_pod_container_name
                    target_label: container
                  - action: replace
                    replacement: /var/log/pods/*$1/*.log
                    separator: /
                    source_labels:
                      - __meta_kubernetes_pod_uid
                      - __meta_kubernetes_pod_container_name
                    target_label: __path__
          
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
        
        fluent-bit:
          enabled: false
        
        grafana:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki
  namespace: loki
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
