apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://dl.gitea.com/charts/
    targetRevision: 10.6.0
    chart: gitea
    helm:
      values: |
        global:
          imagePullSecrets: []
        
        image:
          repository: gitea/gitea
          tag: latest
          pullPolicy: Always
        
        replicaCount: 1
        
        service:
          http:
            type: ClusterIP
            port: 3000
            clusterIP: None
          ssh:
            type: ClusterIP
            port: 22
            clusterIP: None
        
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: gitea.malefstorm.ru
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: gitea-tls
              hosts:
                - gitea.malefstorm.ru
        
        persistence:
          enabled: true
          storageClass: local-path
          size: 10Gi
        
        gitea:
          admin:
            username: malef
            password: ViVa1994
            email: vakfuder@gmail.com
          config:
            server:
              DOMAIN: gitea.malefstorm.ru
              ROOT_URL: https://gitea.malefstorm.ru
              SSH_DOMAIN: gitea.malefstorm.ru
              SSH_PORT: 22
              SSH_LISTEN_PORT: 2222
              OFFLINE_MODE: false
            database:
              DB_TYPE: postgres
              HOST: gitea-postgresql.gitea.svc.cluster.local:5432
              NAME: gitea
              USER: gitea
              PASSWD: changeme
            cache:
              HOST: gitea-valkey.gitea.svc.cluster.local:6379
              ADAPTER: valkey
        
        postgresql:
          enabled: true
          global:
            postgresql:
              auth:
                username: gitea
                password: changeme
                database: gitea
          primary:
            persistence:
              enabled: true
              storageClass: local-path
              size: 10Gi
        
        postgresql-ha:
          enabled: false
        
        valkey:
          enabled: true
          architecture: standalone
          auth:
            enabled: false
          master:
            persistence:
              enabled: true
              storageClass: local-path
              size: 5Gi
        
        valkey-cluster:
          enabled: false
        
        redis-cluster:
          enabled: false
        
        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
